// 389. Find the Difference



// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.





/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let map = new Map();

    // Fill the map with the frequency of each character in string `s`
    for (let letter of s) {
        if (map.has(letter)) {
            let count = map.get(letter);
            map.set(letter, count + 1);
        } else {
            map.set(letter, 1);
        }
    }

    // Iterate through string `t` to find the extra character
    for (let l of t) {
        if (!map.has(l)) {
            // If a character is not in the map, it's the extra character
            return l;
        } else {
            let count = map.get(l);
            if (count === 0) {
                // If the count reaches zero, it's the extra character
                return l;
            } else {
                // Decrement the count of the character
                map.set(l, count - 1);
            }
        }
    }
};
